### ISSUE TITLE
Rust moment

### ISSUE THREAD

**Issue by AlessTheDev** [RoysManfo/Flux#49]
Rust could significantly enhance the performance and reliability of the "flux" terminal, which is currently implemented in Python. One of the key advantages of Rust lies in its focus on memory safety without sacrificing performance. By rewriting "flux" in Rust, you would likely experience a reduction in memory-related errors and vulnerabilities, ensuring a more robust and secure terminal environment.

Rust's ownership system and borrowing mechanism can prevent common programming errors like null pointer dereferencing and data races. This inherent memory safety feature not only contributes to the overall stability of the "flux" terminal but also reduces the likelihood of crashes and unexpected behavior during execution.

Furthermore, Rust's emphasis on zero-cost abstractions and control over system resources allows for efficient utilization of hardware, leading to improved performance. This is particularly beneficial for a terminal application where responsiveness and low-latency interactions are crucial. Users would likely experience a smoother and more seamless command-line interface with faster execution times for various operations.

The community support and growing ecosystem around Rust can also be advantageous for the development of "flux." Access to a wealth of libraries and tools can streamline the implementation of new features or improvements, fostering a more dynamic and extensible terminal experience.

In summary, adopting Rust for the "flux" terminal holds the promise of enhanced memory safety, improved performance, and a more robust foundation for future development, ultimately elevating the user experience in comparison to the current Python implementation.

**Comment by Furetto126** [comment]
I agree! I think that the advantages of using such language will help tremendously with the performance issues (+10 femboy points).

**Comment by RoysManfo** [comment]
It doesn't make sense to rewrite the whole thing at this point, the app is _mostly_ stable anyway.

> Adopting rust for the "flux" terminal holds the promise of enhanced memory safety

This can be solved with rigorous tests, that I am currently writing.

>  I think that the advantages of using such language will help 
tremendously with the performance issues (+10 femboy points).

I don't know if I need those points actually, maybe in the future I will reconsider your offer, but for now, performance isn't as a priority as stability, which is what I am currently working on.

**Comment by roysmanfo** [comment]
I also forgot that memory safety is not a problem in python as in C or C++ because of the abstraction.
So rewriting the app in rust would solve a problem that basically isn't there.

_I do not work with raw memory chunks using stuff like `malloc` or `realloc` nor do weird stuff with pointers to pointers to functions that return other pointers to pointers to the app version (a pointer to an array of chars)_
